# --- Main Colors ---
background            #121413
foreground            #e3e2e1
cursor                #e3e2e1
cursor_text_color     #121413

selection_background  #394a48
selection_foreground  #d3e6e4

url_color             #b0ccc9

# --- ANSI Colors ---
color0                #121413
color1                #ffb4ab
color2                #b0ccc9
color3                #bec9c7
color4                #b8cac8
color5                #b0ccc9
color6                #bec9c7
color7                #e3e2e1

color8                #464746
color9                #93000a
color10               #324b49
color11               #3f4948
color12               #394a48
color13               #3f4948
color14               #324b49
color15               #c7c6c5

# --- Starship Prompt Bubbles ---
color255              #394a48
color254              #b8cac8
color253              #3f4948
color252              #bec9c7
color251              #324b49
color250              #b0ccc9
color249              #93000a
color248              #ffb4ab

color232              #d3e6e4
color233              #233332
color234              #dae5e3
color235              #293231
color236              #cce8e5
color237              #1b3533
color238              #ffdad6
color239              #690005
color240              #d3e6e4

# Matched with unthemed light/dark
color243              #b8cac8
color244              #ffb4ab
color245              #464746

# --- UI Elements ---
active_tab_foreground   #233332
active_tab_background   #b8cac8
inactive_tab_foreground #d3e6e4
inactive_tab_background #394a48

active_border_color     #b8cac8
inactive_border_color   #919190

# --- Marks ---
mark1_foreground        #0e1e1d
mark1_background        #d3e6e4
mark2_foreground        #141d1c
mark2_background        #dae5e3
mark3_foreground        #051f1e
mark3_background        #cce8e5
