set -g mouse on
set -g prefix C-a
set -g base-index 1 # start windows numbering at 1
setw -g pane-base-index 1
set -g renumber-windows on
set -sg escape-time 10

bind-key h select-pane -L
bind-key j select-pane -D 
bind-key k select-pane -U 
bind-key l select-pane -R
bind-key -n M-p previous-window
bind-key -n M-n next-window

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind v display-popup -EE -d "#{pane_current_path}"

##
# Styling
##

set-option -g status-position bottom

set -g @background "#141B1E"
set -g @foreground "#DADADA"
set -g @lighter_background "#232A2D"
set -g @red "#E57474"
set -g @green "#8CCF7E"
set -g @yellow "#e5C76B"
set -g @blue "#67b0E8"
set -g @magenta "#c47FD5"
set -g @cyan "#6cbfBF"
set -g @light_gray "#B3B9B8"

set-option -g status-style "bg=#{@lighter_background}","fg=#{@foreground}"

set -g status-left "  #[fg=#{@green}][#{session_name} :: #{session_windows}]"

set -g status-justify absolute-centre

set -g window-status-format "#I :: #W"
set -g window-status-current-format "#[fg=#{@blue}][#I :: #W]"

set -g status-right "#[fg=#{@yellow}][%H:%M $ %d-%b]  "
